version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nativore-db
    environment:
      POSTGRES_USER: nativore
      POSTGRES_PASSWORD: nativore123
      POSTGRES_DB: nativore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - nativore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nativore"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nativore-backend
    environment:
      DATABASE_URL: postgresql://nativore:nativore123@postgres:5432/nativore
      SECRET_KEY: your-production-secret-key-change-this
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:19006
      DEBUG: "True"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nativore-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nativore-frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - nativore-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  nativore-network:
    driver: bridge
